import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, isAbsolute, resolve } from 'node:path'
import { fromUrl, fromString } from './index.js'
import type { ApitypeConfig, EndpointConfig, GenerateResult } from './types.js'

export interface BatchResult {
  endpoint: EndpointConfig
  result: GenerateResult
  outPath: string
  error?: string
}

export interface BatchOptions {
  cwd?: string
  onProgress?: (ep: EndpointConfig, i: number, total: number) => void
  onDone?: (r: BatchResult) => void
  onError?: (ep: EndpointConfig, err: Error) => void
}

function resolveOut(out: string, cwd: string): string {
  return isAbsolute(out) ? out : resolve(cwd, out)
}

function isUrl(str: string): boolean {
  return str.startsWith('http://') || str.startsWith('https://')
}

export async function runBatch(
  config: ApitypeConfig,
  opts: BatchOptions = {}
): Promise<BatchResult[]> {
  const cwd = opts.cwd ?? process.cwd()
  const { endpoints, defaults } = config
  const results: BatchResult[] = []

  for (let i = 0; i < endpoints.length; i++) {
    const ep = endpoints[i]!
    opts.onProgress?.(ep, i + 1, endpoints.length)

    // Merge defaults
    const merged: EndpointConfig = {
      samples: defaults?.samples,
      timeout: defaults?.timeout,
      fetchWrapper: defaults?.fetchWrapper,
      ...ep,
      headers: { ...defaults?.headers, ...ep.headers },
    }

    const baseOpts = {
      name: merged.name,
      format: merged.format ?? defaults?.format ?? 'zod',
      fetchWrapper: merged.fetchWrapper ?? false,
      sourceUrl: isUrl(merged.url) ? merged.url : undefined,
    } as const

    try {
      const result = isUrl(merged.url)
        ? await fromUrl(merged.url, {
            ...baseOpts,
            samples: merged.samples ?? 1,
            headers: merged.headers,
            timeout: merged.timeout ?? 10_000,
          })
        : fromString(
            (await import('node:fs')).readFileSync(resolve(cwd, merged.url), 'utf8'),
            baseOpts
          )

      const outPath = resolveOut(merged.out, cwd)
      mkdirSync(dirname(outPath), { recursive: true })

      const banner = `// Generated by apitype — do not edit manually\n// Source: ${merged.url}\n\n`
      writeFileSync(outPath, banner + result.combined + '\n', 'utf8')

      const batchResult: BatchResult = { endpoint: ep, result, outPath }
      results.push(batchResult)
      opts.onDone?.(batchResult)
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err)
      opts.onError?.(ep, err instanceof Error ? err : new Error(error))
      results.push({ endpoint: ep, result: { combined: '', format: 'zod' }, outPath: '', error })
    }
  }

  return results
}
