/**
 * Vite plugin for apitype — auto-generates types at dev server start and build.
 *
 * @example
 * // vite.config.ts
 * import { apitype } from 'apitype/vite'
 *
 * export default defineConfig({
 *   plugins: [
 *     apitype({
 *       endpoints: [
 *         { url: 'https://api.example.com/users/1', name: 'User', out: 'src/types/user.ts' },
 *       ],
 *     }),
 *   ],
 * })
 */
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import type { OutputFormat } from './types.js'

export interface ApitypeViteEndpoint {
  url: string
  name: string
  out: string
  headers?: Record<string, string>
  samples?: number
  format?: OutputFormat
  fetchWrapper?: boolean
}

export interface ApitypeViteOptions {
  endpoints: ApitypeViteEndpoint[]
  defaults?: {
    format?: OutputFormat
    fetchWrapper?: boolean
    headers?: Record<string, string>
  }
  /** Only regenerate if the output file doesn't exist (default: false) */
  skipIfExists?: boolean
  /** Log output (default: true) */
  verbose?: boolean
}

export function apitype(options: ApitypeViteOptions) {
  const { endpoints, defaults, skipIfExists = false, verbose = true } = options

  const log = (msg: string) => {
    if (verbose) console.log(`\x1b[36m[apitype]\x1b[0m ${msg}`)
  }

  return {
    name: 'vite-plugin-apitype',
    async buildStart() {
      const { fromUrl } = await import('./index.js')

      for (const ep of endpoints) {
        const outPath = resolve(process.cwd(), ep.out)

        if (skipIfExists && existsSync(outPath)) {
          log(`skipping ${ep.name} (file exists)`)
          continue
        }

        try {
          log(`generating ${ep.name} from ${ep.url}…`)

          const result = await fromUrl(ep.url, {
            name: ep.name,
            format: ep.format ?? defaults?.format ?? 'zod',
            fetchWrapper: ep.fetchWrapper ?? defaults?.fetchWrapper ?? false,
            headers: { ...defaults?.headers, ...ep.headers },
            samples: ep.samples ?? 1,
          })

          mkdirSync(dirname(outPath), { recursive: true })
          const banner = `// Generated by apitype — do not edit manually\n// Source: ${ep.url}\n\n`
          writeFileSync(outPath, banner + result.combined + '\n', 'utf8')
          log(`✓ ${ep.name} → ${ep.out}`)
        } catch (err) {
          console.error(`\x1b[31m[apitype]\x1b[0m Failed to generate ${ep.name}: ${(err as Error).message}`)
        }
      }
    },
  }
}
